version: 2.1

jobs:
  prepare:
    docker:
      - image: mbedos/mbed-os-env:latest
    steps:
      - checkout
      - run: |
          mbed deploy
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_mbed:
    docker:
      - image: mbedos/mbed-os-env:stable
    parameters:
      toolchain:
        type: string
      target:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run: mbed compile -t << parameters.toolchain >> -m << parameters.target >> || exit 1

  build_cmake:
    docker:
      - image: mbedos/mbed-os-env:latest
    parameters:
      toolchain:
        type: string
      target:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run: python3 -m pip install mbed-tools --upgrade # remove after docker image is updated to contain new tools
      - run: mbed-tools compile -t << parameters.toolchain >> -m << parameters.target >> || exit 1

workflows:
  workflow:
    jobs:
      - prepare
      - build_mbed:
          requires:
            - prepare
          matrix:
            parameters:
              target: ["DISCO_l496AG", "WIO_3G", "NRF52840_DK"]
              toolchain: ["GCC_ARM"]
          name: build-mbed-<< matrix.target >>-<< matrix.toolchain >>
      # disabled until cmake is fixed in mbed-os
      #- build_cmake:
      #    requires:
      #      - prepare
      #    matrix:
      #      parameters:
      #        target: ["DISCO_l496AG", "WIO_3g", "NRF52840_DK"]
      #        toolchain: ["GCC_ARM", "ARMC6"]
      #    name: build-cmake-<< matrix.target >>-<< matrix.toolchain >>